### ISSUE TITLE
频繁切换线程出现delay

### ISSUE THREAD

**Issue by zhandroids** [cangHW/Android-Cloud#1]
在主线程和子线程频繁切换后，会出现延迟现象

**Comment by cangHW** [comment]
你好，你说的应该是工具库中的线程调度框架，并且使用的是串行任务，串行任务需要等待上一个任务执行完成后才会开启下一个任务，如果不需要串行，建议使用并行任务

**Comment by cangHW** [comment]
线程切换位于一个独立线程进行工作，所以并不会造成主线程耗时

**Comment by zhandroids** [comment]
使用了并行框架以后，延迟问题已经解决
